version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - ../.env
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-network

volumes:
  mongodb_data:

networks:
  backend-network:
    driver: bridge