version: '3.8'

services:
  iamservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4568:4568"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend-network
    command: sh -c "npx prisma migrate dev --name init && npx prisma generate && npm run swagger && npm run dev"
  
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin_1234
      MYSQL_DATABASE: IAM-Donge-Backend
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-padmin_1234"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - backend-network

volumes:
  mysql_data:
  redis_data:

networks:
  backend-network: